---
title: CahBot Discord Bot
repotitle: CahBot
description: A Discord bot that’s kinda cool that’s being updated frequently, written in Ruby
author: The CB Team
authorurl: http://github.com/Cahbots
url: http://ruby.cahbot.pro
