---
title: CahBot Discord Bot
repotitle: CahBot
description: A Discord bot that’s kinda cool that’s being updated frequently, written in Ruby
author: 2003cah and Chewsterchew
url: http://ruby.cahbot.pro
